name: Docker Update Info

on:
  workflow_dispatch:

jobs:
  Update_Info:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Update repo description
        uses: peter-evans/dockerhub-description@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
          repository: dspwiki/wiki-pre