name: Docker Build & Update

on:
  workflow_dispatch:
  push:
    branches:
      - '*'

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      -
        name: Get current date
        id: date
        run: echo "::set-output name=date::$(date +'%Y-%m-%d')"
      -
        name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      -
        name: Build and push
        uses: docker/build-push-action@v5
        with:
          push: true
          tags: |
            dspwiki/wiki-pre:latest
            dspwiki/wiki-pre:${{ steps.date.outputs.date }}
